name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What’s the underlying problem or use case?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature and how it would work.
    validations:
      required: true
  - type: textarea
    id: alt
    attributes:
      label: Alternatives
      description: Any alternative solutions you’ve considered?
  - type: textarea
    id: extra
    attributes:
      label: Additional context / mockups
